# fly.toml file generated for vxu on 2023-03-05T18:54:06-05:00
app = "vxu"
kill_signal = "SIGTERM"
kill_timeout = 5

[experimental]
  auto_rollback = true

[deploy]
  release_command = "/app/bin/migrate"

[env]
  PHX_HOST = "vxu.fly.dev"
  PORT = "8080"
  PRIMARY_REGION = "lax"
  RELEASE_COOKIE="iHw000MHvKwjeH3tl6LSOOcbe8asKzaxYBav0BJ8QoFIP3AqJUoceA=="

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0
