import Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :vx_underground, VxUndergroundWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: VxUnderground.Finch, local: false

# Do not print debug messages in production
config :logger, level: :info

config :nostrum, token: System.get_env("DISCORD_BOT_TOKEN"),
  num_shards: 1

config :logger,
  backends: [LoggerDiscordBackend],
  level: :error

config :logger, LoggerDiscordBackend,
  level: :error,
  format: "```$date $time [$level] $message```",
  recipient_id: System.get_env("DISCORD_CHANNEL_ID")

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
