name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      db:
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        image: postgres:16
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: "1.17.2" # Define the elixir version [required]
          otp-version: "27.0.1" # Define the OTP version [required]
      - name: Add EZSuite Repo
        run: |
          mix hex.repo add ezsuite https://ezsuite.dev/repo \
          --auth-key ${{ secrets.EZSUITE_AUTH_KEY }} \
          --fetch-public-key ${{ secrets.EZSUITE_PUBLIC_KEY }}
      - name: Add Fluxon Repo
        run: |
          mix hex.repo add ezsuite https://repo.fluxonui.com \
          --auth-key ${{ secrets.FLUXON_AUTH_KEY }} \
          --fetch-public-key ${{ secrets.FLUXON_PUBLIC_KEY }}
      - name: Restore dependencies cache
        uses: actions/cache@v4
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
      - name: Install dependencies
        run: mix deps.get
      - name: Run tests
        run: MIX_ENV=test mix test.ci

  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    needs: ["test"]
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    # Only deploy if the PR is merged or if the push is to main
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true || github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --build-secret ezsuite_auth_key=${{ secrets.EZSUITE_AUTH_KEY }} --no-cache --push -y --remote-only -a ${{ secrets.APP_NAME }} --build-secret ezsuite_auth_key="${{ secrets.EZSUITE_AUTH_KEY }} --release-command-timeout none --wait-timeout "20m0s""
