name: Fly CI/CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      steps:
        - uses: actions/checkout@v2
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - name: Set Environment Variable from GitHub Secret
          run: echo "APP_NAME=${{ secrets.APP_NAME }}" >> $GITHUB_ENV
        - name: Replace Environment Variables in fly.toml
          run: bash replace-env-vars.sh
        - run: flyctl deploy --remote-only --wait-timeout 500 -a ${{ secrets.APP_NAME }}
