name: Fly CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Build and test
    runs-on: ubuntu-latest
    services:
      db:
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        image: postgres:14
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      PARAXIAL_API_KEY: ${{ secrets.PARAXIAL_API_KEY }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.15.6' # Define the elixir version [required]
        otp-version: '26.2.1' # Define the OTP version [required]
    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies
      run: mix deps.get
    - name: Run tests
      run: MIX_ENV=test mix test.ci
    - name: Get Github Repo Name
      run: echo "REPO_NAME=$(echo ${{ github.repository }} | cut -d'/' -f2)" >> $GITHUB_ENV
    - name: Send info to Paraxial.io
      run: |
        mix paraxial.scan --github_app \
          --install_id 45585617 \
          --repo_owner ${{ github.repository_owner }} \
          --repo_name ${{ env.REPO_NAME }} \
          --pr_number ${{ github.event.number }} \
          --add-exit-code
  deploy:
      name: Deploy app
      needs: test
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      runs-on: ubuntu-latest
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      steps:
        - uses: actions/checkout@v2
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - name: Set Environment Variable from GitHub Secret
          run: echo "APP_NAME=${{ secrets.APP_NAME }}" >> $GITHUB_ENV
        - name: Replace Environment Variables in fly.toml
          run: bash replace-env-vars.sh
        - run: flyctl deploy --remote-only --wait-timeout 500 -a ${{ secrets.APP_NAME }}
